---
name: Pedro
surname: Neto
position: "Estudante de Sistemas de Informação - CIn - UFPE"
address: "Recife, Pernambuco"
phone: +55 87 99995-2777
www: mariecurie.com
email: "pccn@cin.ufpe.br"
twitter: pedroissoai
github: pedroceciliocn
linkedin: pedroceciliocn
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::twentyseconds:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Educação

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Administração", "2019-2020", "UNIVASF", "Petrolina, Pernambuco",
  "Sistemas de Informação", "2020-2024", "UFPE", "Recife, Pernambuco",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

<!-- # Nobel Prizes -->

<!-- ```{r} -->
<!-- tribble( -->
<!--   ~Year, ~Type, ~Desc, -->
<!--   1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel", -->
<!--   1911, "Chemistry", "Awarded for the discovery of radium and polonium" -->
<!-- ) %>%  -->
<!--   brief_entries( -->
<!--     glue::glue("Nobel Prize in {Type}"), -->
<!--     Year,  -->
<!--     Desc -->
<!--   ) -->
<!-- ``` -->

<!-- # Publications -->

<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- knitr::write_bib(c("vitae", "tibble"), "packages.bib") -->

<!-- bibliography_entries("packages.bib") %>% -->
<!--   arrange(desc(author$family), issued) -->
<!-- ``` -->

